### ISSUE TITLE
ReadMe update

### ISSUE THREAD

**Issue by derins** [slacgismo/SCRIPT#116]
Just saw this - https://github.com/slacgismo/SCRIPT/pull/113#issuecomment-726397621

**Comment by derins** [comment]
Hey @avpeery, it seems like you accidentally closed this issue - I had missed Jonathan's comment in my last PR so this is an issue referring to that

**Comment by avpeery** [comment]
@derins  ah my mistake, I thought it was addressed. Thanks

**Comment by derins** [comment]
no worries
