### ISSUE TITLE
provide APIs to get defualt parameter combinations

### ISSUE THREAD

**Issue by hooshooo** [slacgismo/SCRIPT#57]
The new models for default paprameter conbinations will serve as the foreign key of the corresponding algorithm result models.

**Comment by hooshooo** [comment]
I'm working on [add_api_for_default_para_combinations](https://github.com/slacgismo/SCRIPT/tree/add_api_for_default_para_combinations) for webserver support.

**Comment by proverbs** [comment]
I add a `name` field to all the models of parameter conbinations, and I think we should provide users with a web interface to CRUD the names. @wyq730

**Comment by hooshooo** [comment]
finished: https://github.com/slacgismo/SCRIPT/pull/70

**Comment by hooshooo** [comment]
merged
