### ISSUE TITLE
add a `refresh` button on the main page

### ISSUE THREAD

**Issue by hooshooo** [slacgismo/SCRIPT#62]
Add a `refresh` button on the main page to allow users to notify ec2 that they have uploaded new data and ask ec2 to process the data for the **overview** page.
As the reponse, we should tell users how many data we have processed.

**Comment by wyq730** [comment]
Only for overview page? Or also for algorithm pages? @proverbs

**Comment by hooshooo** [comment]
> Only for overview page? Or also for algorithm pages? @proverbs

Only for overview page. As I mentioned in https://github.com/slacgismo/SCRIPT/issues/63 , I think it would be better if ec2 will never start a active computation without being requested.
